<a href="https://colab.research.google.com/github/rameshbabuatreyu/AI-ML/blob/master/NLP_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
project_path = "/content/drive/My Drive/glove.6B.zip"

In [12]:
from zipfile import ZipFile
with ZipFile(project_path+'glove.6B.zip', 'r') as z:
  z.extractall()

FileNotFoundError: ignored

In [0]:
import pandas as pd

In [7]:
pwd

'/content'

In [0]:

import numpy as np

In [0]:
import os

In [0]:
body=pd.read_csv('/content/train_bodies.csv')

In [0]:
stance=pd.read_csv('/content/train_stances.csv')

In [0]:
dataset=body.merge(stance,on='Body ID')

In [30]:
dataset.head()

Body ID  ...     Stance
0        0  ...  unrelated
1        0  ...  unrelated
2        0  ...  unrelated
3        0  ...  unrelated
4        0  ...  unrelated

[5 rows x 4 columns]

In [0]:
MAX_NB_WORDS = 20000
MAX_SENTS = 20
MAX_SENTS_HEADING = 1
MAX_SENT_LENGTH = 20
VALIDATION_SPLIT = 0.2

In [32]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [33]:
import keras
from __future__ import print_function

from keras.models import Model
from keras.layers import Input, LSTM, Dense
import numpy as np

Using TensorFlow backend.


In [0]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from keras_preprocessing import text

text_to_word_sequence = text.text_to_word_sequence
one_hot = text.one_hot
hashing_trick = text.hashing_trick
Tokenizer = text.Tokenizer
tokenizer_from_json = text.tokenizer_from_json

In [0]:
tokeniser=keras.preprocessing.text.Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ', char_level=False, oov_token=None, document_count=0)

In [0]:
#texts=dataset['articleBody'].values.tolist()
texts=dataset['articleBody']+dataset['Headline']
labels=dataset['Headline'].values.tolist()

In [37]:
texts

0        A small meteorite crashed into a wooded area i...
1        A small meteorite crashed into a wooded area i...
2        A small meteorite crashed into a wooded area i...
3        A small meteorite crashed into a wooded area i...
4        A small meteorite crashed into a wooded area i...
                               ...                        
49967    ANN ARBOR, Mich. – A pizza delivery man in Mic...
49968    ANN ARBOR, Mich. – A pizza delivery man in Mic...
49969    ANN ARBOR, Mich. – A pizza delivery man in Mic...
49970    ANN ARBOR, Mich. – A pizza delivery man in Mic...
49971    ANN ARBOR, Mich. – A pizza delivery man in Mic...
Length: 49972, dtype: object

In [0]:
tokeniser.fit_on_texts(texts)

In [0]:
sequences=tokeniser.texts_to_sequences(texts)

In [0]:
word_index=tokeniser.word_index

In [41]:
print(len(word_index))

33642


In [0]:
from nltk import sent_tokenize
#articles=sent_tokenize(''.join(texts))

In [0]:
texts=[]
articles=[]
for i in range(len(dataset['articleBody'])):
  texts.append(dataset['articleBody'].iloc[i])
  articles.append(sent_tokenize(dataset['articleBody'].iloc[i]))

In [44]:
print(tokeniser.word_index)

{'the': 1, 'to': 2, 'a': 3, 'of': 4, 'in': 5, 'and': 6, 'that': 7, 'is': 8, 'was': 9, 'on': 10, 'for': 11, 'said': 12, 'he': 13, 'with': 14, 'it': 15, 'his': 16, 'have': 17, 'as': 18, 'by': 19, 'has': 20, 'at': 21, 'from': 22, 'be': 23, 'an': 24, 'not': 25, 'are': 26, 'been': 27, 'but': 28, 'who': 29, '”': 30, 'this': 31, 'had': 32, 'they': 33, 'after': 34, 'i': 35, 'were': 36, 'we': 37, 'will': 38, 'about': 39, 'one': 40, 'or': 41, 'isis': 42, 'which': 43, 'video': 44, 'she': 45, 'apple': 46, 'state': 47, 'up': 48, 'her': 49, 'would': 50, 'their': 51, 'more': 52, 'also': 53, 'when': 54, 'told': 55, 'new': 56, 'out': 57, 'no': 58, 'all': 59, 'people': 60, 'there': 61, 'you': 62, 'its': 63, 'if': 64, 'him': 65, 'man': 66, 'news': 67, 'islamic': 68, 'could': 69, 'what': 70, 'year': 71, 'watch': 72, 'time': 73, 'al': 74, 'over': 75, 'some': 76, 'group': 77, 'according': 78, 's': 79, 'u': 80, 'into': 81, 'first': 82, 'so': 83, 'being': 84, 'reports': 85, 'just': 86, 'last': 87, 'syria': 88

In [45]:
texts[0]

'A small meteorite crashed into a wooded area in Nicaragua\'s capital of Managua overnight, the government said Sunday. Residents reported hearing a mysterious boom that left a 16-foot deep crater near the city\'s airport, the Associated Press reports. \n\nGovernment spokeswoman Rosario Murillo said a committee formed by the government to study the event determined it was a "relatively small" meteorite that "appears to have come off an asteroid that was passing close to Earth." House-sized asteroid 2014 RC, which measured 60 feet in diameter, skimmed the Earth this weekend, ABC News reports. \nMurillo said Nicaragua will ask international experts to help local scientists in understanding what happened.\n\nThe crater left by the meteorite had a radius of 39 feet and a depth of 16 feet,  said Humberto Saballos, a volcanologist with the Nicaraguan Institute of Territorial Studies who was on the committee. He said it is still not clear if the meteorite disintegrated or was buried.\n\nHumbe

In [46]:
articles[0]

["A small meteorite crashed into a wooded area in Nicaragua's capital of Managua overnight, the government said Sunday.",
 "Residents reported hearing a mysterious boom that left a 16-foot deep crater near the city's airport, the Associated Press reports.",
 'Government spokeswoman Rosario Murillo said a committee formed by the government to study the event determined it was a "relatively small" meteorite that "appears to have come off an asteroid that was passing close to Earth."',
 'House-sized asteroid 2014 RC, which measured 60 feet in diameter, skimmed the Earth this weekend, ABC News reports.',
 'Murillo said Nicaragua will ask international experts to help local scientists in understanding what happened.',
 'The crater left by the meteorite had a radius of 39 feet and a depth of 16 feet,  said Humberto Saballos, a volcanologist with the Nicaraguan Institute of Territorial Studies who was on the committee.',
 'He said it is still not clear if the meteorite disintegrated or was bu

In [0]:

data=np.zeros((len(articles),MAX_SENTS,MAX_SENT_LENGTH))

In [48]:
data.shape

(49972, 20, 20)

In [0]:
word_index=tokeniser.word_index

In [50]:
word_index['trump']

13309

In [51]:
for j in range(0,len(articles)):
  for i in range(0,len(articles[j])):
    if(i<=20):
      words=text_to_word_sequence(articles[j][i])
    for k in range(0,20):
      if(k<=len(words)-1):
        print(words[k])
        data[j,i,k]=word_index[words[k]]
      else:
        data[j,i,k]=0

a
small
meteorite
crashed
into
a
wooded
area
in
nicaragua's
capital
of
managua
overnight
the
government
said
sunday
residents
reported
hearing
a
mysterious
boom
that
left
a
16
foot
deep
crater
near
the
city's
airport
the
associated
press
government
spokeswoman
rosario
murillo
said
a
committee
formed
by
the
government
to
study
the
event
determined
it
was
a
relatively
house
sized
asteroid
2014
rc
which
measured
60
feet
in
diameter
skimmed
the
earth
this
weekend
abc
news
reports
murillo
said
nicaragua
will
ask
international
experts
to
help
local
scientists
in
understanding
what
happened
the
crater
left
by
the
meteorite
had
a
radius
of
39
feet
and
a
depth
of
16
feet
said
humberto
he
said
it
is
still
not
clear
if
the
meteorite
disintegrated
or
was
buried
humberto
garcia
of
the
astronomy
center
at
the
national
autonomous
university
of
nicaragua
said
the
meteorite
could
be
related
to
we
have
to
study
it
more
because
it
could
be
ice
or
rock
he
said
wilfried
strauch
an
adviser
to
the
institute


IndexError: ignored

In [52]:
data[2, :, :]

array([[3.0000e+00, 4.8500e+02, 4.3300e+02, 7.2040e+03, 8.1000e+01,
        3.0000e+00, 3.7320e+03, 3.3100e+02, 5.0000e+00, 3.8880e+03,
        3.5000e+02, 4.0000e+00, 1.4320e+03, 2.9560e+03, 1.0000e+00,
        8.9000e+01, 1.2000e+01, 4.6400e+02, 0.0000e+00, 0.0000e+00],
       [7.5700e+02, 9.5000e+01, 1.0450e+03, 3.0000e+00, 2.6750e+03,
        1.7500e+03, 7.0000e+00, 1.8800e+02, 3.0000e+00, 1.2170e+03,
        1.0740e+03, 2.0260e+03, 6.9800e+02, 1.5800e+02, 1.0000e+00,
        3.0290e+03, 4.4900e+02, 1.0000e+00, 5.5500e+02, 2.4300e+02],
       [8.9000e+01, 1.0650e+03, 4.1110e+03, 2.3450e+03, 1.2000e+01,
        3.0000e+00, 1.0920e+03, 3.3000e+03, 1.9000e+01, 1.0000e+00,
        8.9000e+01, 2.0000e+00, 1.7910e+03, 1.0000e+00, 5.2900e+02,
        2.0050e+03, 1.5000e+01, 9.0000e+00, 3.0000e+00, 3.1070e+03],
       [1.8600e+02, 3.6390e+03, 9.7100e+02, 2.0200e+02, 2.5530e+03,
        4.3000e+01, 6.7700e+03, 1.7190e+03, 1.2500e+03, 5.0000e+00,
        1.3306e+04, 1.7921e+04, 1.0000e+00, 7

In [53]:
data[0, :, :]

array([[3.0000e+00, 4.8500e+02, 4.3300e+02, 7.2040e+03, 8.1000e+01,
        3.0000e+00, 3.7320e+03, 3.3100e+02, 5.0000e+00, 3.8880e+03,
        3.5000e+02, 4.0000e+00, 1.4320e+03, 2.9560e+03, 1.0000e+00,
        8.9000e+01, 1.2000e+01, 4.6400e+02, 0.0000e+00, 0.0000e+00],
       [7.5700e+02, 9.5000e+01, 1.0450e+03, 3.0000e+00, 2.6750e+03,
        1.7500e+03, 7.0000e+00, 1.8800e+02, 3.0000e+00, 1.2170e+03,
        1.0740e+03, 2.0260e+03, 6.9800e+02, 1.5800e+02, 1.0000e+00,
        3.0290e+03, 4.4900e+02, 1.0000e+00, 5.5500e+02, 2.4300e+02],
       [8.9000e+01, 1.0650e+03, 4.1110e+03, 2.3450e+03, 1.2000e+01,
        3.0000e+00, 1.0920e+03, 3.3000e+03, 1.9000e+01, 1.0000e+00,
        8.9000e+01, 2.0000e+00, 1.7910e+03, 1.0000e+00, 5.2900e+02,
        2.0050e+03, 1.5000e+01, 9.0000e+00, 3.0000e+00, 3.1070e+03],
       [1.8600e+02, 3.6390e+03, 9.7100e+02, 2.0200e+02, 2.5530e+03,
        4.3000e+01, 6.7700e+03, 1.7190e+03, 1.2500e+03, 5.0000e+00,
        1.3306e+04, 1.7921e+04, 1.0000e+00, 7

In [0]:
text_headings = list(dataset['Headline'])
articles_headings = []

In [55]:
articles = [] 
[text_headings[0].split('.')]

[['Soldier shot, Parliament locked down after gunfire erupts at war memorial']]

In [0]:
import re
BAD_SYMBOLS_RE=re.compile('[^a-zA-Z0-9 ]')
for j in range(0,len(articles_headings)):
  for i in range(0,len(articles_headings[j])):
    articles_headings[j][i] = re.sub(BAD_SYMBOLS_RE,'',articles_headings[j][i])

In [57]:
text_headings[0]

'Soldier shot, Parliament locked down after gunfire erupts at war memorial'

In [60]:
articles_headings[0]

IndexError: ignored

In [0]:
data_headings=np.zeros((len(articles_headings),MAX_SENTS,MAX_SENT_LENGTH))

In [0]:

for j in range(0,len(articles_headings)):
  for i in range(0,len(articles_headings[j])):
    if(i<=20):
      words=text_to_word_sequence(articles_headings[j][i])
    for k in range(0,20):
      if(k<=len(words)-1):
        print(words[k])
        data_heading[j,i,k]=word_index[words[k]]
      else:
        data_heading[j,i,k]=0

In [62]:
data_headings[0,:,:]

IndexError: ignored

In [0]:
labels = pd.get_dummies(dataset['Stance'])

In [64]:
print('Shape of data tensor:', data.shape)
print('Shape of label tensor:', labels.shape)

Shape of data tensor: (49972, 20, 20)
Shape of label tensor: (49972, 4)


In [65]:
## get numbers upto no.of articles
indices = np.arange(data.shape[0])
## shuffle the numbers
np.random.shuffle(indices)
indices

array([ 5488, 24668,  2037, ..., 47187, 33879, 36615])

In [66]:

## shuffle the data
data = data[indices]

## shuffle the labels according to data
labels = labels[indices]

KeyError: ignored

In [67]:
data_headings = data_headings[indices]

IndexError: ignored

In [0]:

from sklearn.model_selection import train_test_split
x_train, x_val,y_train,y_val = train_test_split(data, labels, test_size = 0.2, random_state = 0)

In [69]:
x_heading_train, x_heading_val,y_train,y_val = train_test_split(data_headings, labels, test_size = 0.2, random_state = 0)

ValueError: ignored

In [70]:
print(x_train.shape)
print(y_train.shape)

print(x_val.shape)
print(y_val.shape)

(39977, 20, 20)
(39977, 4)
(9995, 20, 20)
(9995, 4)


In [0]:
x_train=np.reshape(x_train, (39977, 400))

In [72]:
np.reshape(x_val, (9995, 400))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('./glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = np.asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

# create a weight matrix for words in training docs
embedding_matrix = np.zeros((len(word_index) + 1, 100))


for word, i in tokeniser.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [75]:
len(word_index) + 1

33643

In [0]:
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional
from keras.optimizers import Adam

In [77]:
model = Sequential()

# Embedding layer
model.add(
    Embedding(
        input_dim=len(word_index) + 1,
        output_dim=100,
        weights=None,
        trainable=True))

# Recurrent layer
model.add(
    LSTM(
        64, return_sequences=False, dropout=0.1,
        recurrent_dropout=0.1))

# Fully connected layer
model.add(Dense(64, activation='relu'))

# Dropout for regularization
model.add(Dropout(0.5))

# Output layer
model.add(Dense(4, activation='softmax'))

# Compile the model
model.compile(
    optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 100)         3364300   
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                42240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 260       
Total params: 3,410,960
Trainable par

In [0]:
h = model.fit(x_train, y_train, epochs = 10, batch_size = 50, 
          verbose = 1)## Train the model




Epoch 1/10





39977/39977 [==============================] - 489s 12ms/step - loss: 0.3606 - acc: 0.8637
Epoch 2/10
38800/39977 [============================>.] - ETA: 14s - loss: 0.3542 - acc: 0.8664